"""create request tables

Revision ID: 8361abc6ef10
Revises: e5be7ccf54d7
Create Date: 2026-03-09 17:04:04.618522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8361abc6ef10'
down_revision: Union[str, Sequence[str], None] = 'e5be7ccf54d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fa_request_entity',
    sa.Column('REQUEST_ID', sa.String(length=255), nullable=False),
    sa.Column('WORKFLOW_NAME', sa.String(length=255), nullable=False),
    sa.Column('START_TIME', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('END_TIME', sa.DateTime(), nullable=True),
    sa.Column('REQUEST_STATUS', sa.Enum('QUEUED', 'EXECUTING', 'SUSPENDED', 'COMPLETED', 'FAILED', name='requeststatus', native_enum=False), nullable=False),
    sa.Column('PAYLOAD', sa.JSON(), nullable=True),
    sa.Column('REMARK', sa.String(length=2000), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=32), nullable=True),
    sa.Column('CREATED_TIME', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('LAST_MODIFIED_BY', sa.String(length=32), nullable=True),
    sa.Column('LAST_MODIFIED_TIME', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('REQUEST_ID')
    )
    op.create_index('idx_request_fa_requeststatus', 'fa_request_entity', ['REQUEST_STATUS'], unique=False)
    op.create_table('fa_task_entity',
    sa.Column('TASK_ID', sa.String(length=255), nullable=False),
    sa.Column('STEP_ID', sa.String(length=255), nullable=False),
    sa.Column('TASK_NAME', sa.String(length=255), nullable=False),
    sa.Column('START_TIME', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('TASK_STATUS', sa.Enum('QUEUED', 'EXECUTNG', 'SUSPENDED', 'RETRY', 'COMPLETED', 'FAILED', name='taskstatus', native_enum=False), nullable=True),
    sa.Column('NEXT_RETRY_AT', sa.DateTime(), nullable=True),
    sa.Column('RETRY_COUNT', sa.Integer(), nullable=True),
    sa.Column('CONTEXT', sa.JSON(), nullable=True),
    sa.Column('REMARK', sa.String(length=2000), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=32), nullable=True),
    sa.Column('CREATED_TIME', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('LAST_MODIFIED_BY', sa.String(length=32), nullable=True),
    sa.Column('LAST_MODIFIED_TIME', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('VERSION', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['fa_request_entity.REQUEST_ID'], ),
    sa.PrimaryKeyConstraint('TASK_ID')
    )
    op.create_index('idx_task_fa_taskstatus', 'fa_task_entity', ['TASK_STATUS'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_fa_taskstatus', table_name='fa_task_entity')
    op.drop_table('fa_task_entity')
    op.drop_index('idx_request_fa_requeststatus', table_name='fa_request_entity')
    op.drop_table('fa_request_entity')
    # ### end Alembic commands ###
